import tactic

namespace natree

  --inductive structure of pre-trees (natural trees pre-quotienting)
  inductive pre 
  | node : pre
  | app : pre → pre → pre

  namespace pre

    notation `𝕋'` := pre
    notation `▢` := pre.node
    infixl `◦`:60 := pre.app

    --reduction rules of tree calculus, specified as an inductive binary relation on pre-trees
    inductive reduces_to : 𝕋' → 𝕋' → Prop
    | kernel         (y) {z} : reduces_to (▢◦   ▢   ◦y◦z) y
    |   stem     (x) (y) (z) : reduces_to (▢◦ (▢◦x) ◦y◦z) (y◦z◦(x◦z))
    |   fork (w) (x) {y} (z) : reduces_to (▢◦(▢◦w◦x)◦y◦z) (z◦w◦x)
    |   left {a₁ a₂ b₁} (h : reduces_to a₁ b₁) : reduces_to (a₁ ◦ a₂) (b₁ ◦ a₂)
    |  right {a₁ a₂ b₂} (h : reduces_to a₂ b₂) : reduces_to (a₁ ◦ a₂) (a₁ ◦ b₂)
    infixr ` ↦ `:60 := reduces_to

    --equivalence relation on pre-trees generated by reflexive, symmetric, transitive closure of (↦)
    instance equiv : setoid 𝕋' := eqv_gen.setoid (↦)

    namespace equiv

      lemma lift_reduces_to {a b} : a ↦ b → a ≈ b :=
      begin
        intro h,
        apply eqv_gen.rel,
        assumption,
      end

      theorem kernel {y z} : (▢◦▢◦y◦z) ≈ y :=
      begin
        apply lift_reduces_to,
        apply reduces_to.kernel,
      end

      theorem stem {x y z} : (▢◦(▢◦x)◦y◦z) ≈ (y◦z◦(x◦z)) :=
      begin
        apply lift_reduces_to,
        apply reduces_to.stem,
      end

      theorem fork {w x y z} : (▢◦(▢◦w◦x)◦y◦z) ≈ (z◦w◦x) :=
      begin
        apply lift_reduces_to,
        apply reduces_to.fork,
      end

      lemma congr_left {a₁ a₂ b₁} : a₁ ≈ b₁ → a₁◦a₂ ≈ b₁◦a₂ :=
      begin
        intro h,
        induction h with x y h _ x y h₁ h₂ x y z h₁ h₂ h₃ h₄,
              apply eqv_gen.rel,
              apply reduces_to.left,
              assumption,
            apply eqv_gen.refl,
          apply eqv_gen.symm,
          assumption,
        apply eqv_gen.trans,
            assumption,
        assumption,
      end

      lemma congr_right {a₁ a₂ b₂} : a₂ ≈ b₂ → a₁◦a₂ ≈ a₁◦b₂ :=
      begin
        intro h,
        induction h with x y h _ x y h₁ h₂ x y z h₁ h₂ h₃ h₄,
              apply eqv_gen.rel,
              apply reduces_to.right,
              assumption,
            apply eqv_gen.refl,
          apply eqv_gen.symm,
          assumption,
        apply eqv_gen.trans,
            assumption,
        assumption,
      end

      theorem congr {a₁ a₂ b₁ b₂} : a₁ ≈ b₁ → a₂ ≈ b₂ → a₁◦a₂ ≈ b₁◦b₂ :=
      begin
        intros h₁ h₂,
        apply eqv_gen.trans,
            apply congr_left,
            assumption,
        apply congr_right,
        assumption,
      end

      --△⬝(△⬝x)⬝y⬝z = y⬝z⬝(x⬝z)
      --△⬝(△⬝△)⬝△⬝△ = △⬝△⬝(△⬝△)
      --(△⬝(△⬝△)⬝△)⬝△ = (△⬝△)⬝(△⬝△)
      --a₁⬝a₂ = b₁⬝b₂ → a₁ = b₁ ∧ a₂ = b₂
      --(△⬝(△⬝△)⬝△) = (△⬝△)
      --△ = (△⬝△)
      ----------------------------------
      --△⬝(△⬝△)⬝△ = △⬝△
      --△ = △⬝△
      --hence this is *false*
      #check @app.inj
      --(◦) is not injective modulo equivalence
      theorem not_inj {a₁ a₂ b₁ b₂} : a₁◦a₂ ≈ b₁◦b₂ → ¬ (a₁ ≈ b₁ ∧ a₂ ≈ b₂) :=
      begin
        sorry
      end

    end equiv

  end pre

end natree