import tactic

namespace natree

  --inductive structure of pre-trees (natural trees pre-quotienting)
  inductive pre 
  | node : pre
  | app : pre → pre → pre

  #print prefix natree.pre --show all generated defs for "pre"

  namespace pre

    notation `𝕋'` := pre
    notation `▢` := pre.node
    infixl `◦`:60 := pre.app

    --reduction rules of tree calculus, specified as an inductive binary relation on pre-trees
    inductive reduces_to : 𝕋' → 𝕋' → Prop
    | kernel         (y) {z} : reduces_to (▢◦   ▢   ◦y◦z) y
    |   stem     (x) (y) (z) : reduces_to (▢◦ (▢◦x) ◦y◦z) (y◦z◦(x◦z))
    |   fork (w) (x) {y} (z) : reduces_to (▢◦(▢◦w◦x)◦y◦z) (z◦w◦x)
    |   left {a₁ a₂ b₁} (h : reduces_to a₁ b₁) : reduces_to (a₁ ◦ a₂) (b₁ ◦ a₂)
    |  right {a₁ a₂ b₂} (h : reduces_to a₂ b₂) : reduces_to (a₁ ◦ a₂) (a₁ ◦ b₂)
    infixr ` ↦ `:60 := reduces_to

    -----------------------------------------------------------------------------------

    --https://xenaproject.wordpress.com/2018/03/24/no-confusion-over-no_confusion/
    #check @pre.no_confusion --what dis? https://leanprover.github.io/theorem_proving_in_lean/induction_and_recursion.html?highlight=no_confusion
    #check @pre.no_confusion_type
    
    lemma how : ¬ ▢ ↦ ▢ := begin --how does this work?
      intro h,
      cases h,
    end
    #print how

    #reduce @decidable_rel
    def decide_reduces_to (a b) : decidable (a ↦ b)
    | (▢◦▢◦y◦z) (y₂) := if y = y₂ then decidable.is_true (reduces_to.kernel a) else decidable.is_false (reduces_to.kernel a)

    -----------------------------------------------------------------------------------

    --equivalence relation on pre-trees generated by reflexive, symmetric, transitive closure of (↦)
    instance equiv : setoid 𝕋' := eqv_gen.setoid (↦)

    namespace equiv

      lemma lift_reduces_to {a b} : a ↦ b → a ≈ b :=
      begin
        intro h,
        apply eqv_gen.rel,
        assumption,
      end

      theorem kernel {y z} : (▢◦▢◦y◦z) ≈ y :=
      begin
        apply lift_reduces_to,
        apply reduces_to.kernel,
      end

      theorem stem {x y z} : (▢◦(▢◦x)◦y◦z) ≈ (y◦z◦(x◦z)) :=
      begin
        apply lift_reduces_to,
        apply reduces_to.stem,
      end

      theorem fork {w x y z} : (▢◦(▢◦w◦x)◦y◦z) ≈ (z◦w◦x) :=
      begin
        apply lift_reduces_to,
        apply reduces_to.fork,
      end

      lemma congr_left {a₁ a₂ b₁} : a₁ ≈ b₁ → a₁◦a₂ ≈ b₁◦a₂ :=
      begin
        intro h,
        induction h with x y h _ x y h₁ h₂ x y z h₁ h₂ h₃ h₄,
              apply eqv_gen.rel,
              apply reduces_to.left,
              assumption,
            apply eqv_gen.refl,
          apply eqv_gen.symm,
          assumption,
        apply eqv_gen.trans,
            assumption,
        assumption,
      end

      lemma congr_right {a₁ a₂ b₂} : a₂ ≈ b₂ → a₁◦a₂ ≈ a₁◦b₂ :=
      begin
        intro h,
        induction h with x y h _ x y h₁ h₂ x y z h₁ h₂ h₃ h₄,
              apply eqv_gen.rel,
              apply reduces_to.right,
              assumption,
            apply eqv_gen.refl,
          apply eqv_gen.symm,
          assumption,
        apply eqv_gen.trans,
            assumption,
        assumption,
      end

      theorem congr {a₁ a₂ b₁ b₂} : a₁ ≈ b₁ → a₂ ≈ b₂ → a₁◦a₂ ≈ b₁◦b₂ :=
      begin
        intros h₁ h₂,
        apply eqv_gen.trans,
            apply congr_left,
            assumption,
        apply congr_right,
        assumption,
      end

      -----------------------------------------------------------------------------------

      --(◦) is not injective modulo equivalence
      theorem not_inj : ¬ (∀ {a₁ a₂ b₁ b₂}, a₁◦a₂ ≈ b₁◦b₂ → a₁ ≈ b₁ ∧ a₂ ≈ b₂) :=
      begin
        intro h₁,
        have h₂ := @stem ▢ ▢ ▢,
        have h₃ := @h₁ (▢◦(▢◦▢)◦▢) ▢ (▢◦▢) (▢◦▢),
        have h₄ := h₃ h₂,
        cases h₄,
        --need reducability and equivalence to have decidable instances (then it'll be much easier)
        --actually equivalence is almost certainly *not* decidable in general
      end

      #reduce to_bool (▢ ↦ ▢◦▢)
      #check @app.inj

      -----------------------------------------------------------------------------------

    end equiv

  end pre

end natree